[package]
name = "HelloRust"
version = "0.1.0"
authors = ["Ben Ege Izmirli", "Paul Houser", "Gideon Wolfe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
